import { archiveEvent, createMaintenance, updateMaintenance } from "@/modules/admin/actions";
import { loadEventFormData, loadMaintenances } from "@/modules/admin/data";
import { requireAdmin } from "@/modules/auth/guard";
import { Notice, PageHeader, Unavailable } from "../_components";
import styles from "../admin.module.css";

export default async function MaintenancePage({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string }> }) {
  await requireAdmin();
  const [formData, records, params] = await Promise.all([loadEventFormData(), loadMaintenances(), searchParams]);
  return <><PageHeader title="Maintenance" description="Plan maintenance windows, record actual timing, and choose whether each event reduces uptime." /><Notice {...params} />
    {!formData.available ? <Unavailable message={formData.message} /> : <section className={styles.panel}><h2>Schedule maintenance</h2><form action={createMaintenance} className={styles.form}>
      <label className={styles.field}>Slug<input name="slug" required /></label><label className={styles.field}>Status<select name="status"><option value="scheduled">Scheduled</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label>
      <label className={styles.field}>English title<input name="titleEn" required /></label><label className={styles.field}>Italian title<input name="titleIt" required /></label><label className={styles.field}>English description<textarea name="descriptionEn" /></label><label className={styles.field}>Italian description<textarea name="descriptionIt" /></label>
      <label className={styles.field}>Scheduled start (UTC)<input name="scheduledStartAt" type="datetime-local" required /></label><label className={styles.field}>Scheduled end (UTC)<input name="scheduledEndAt" type="datetime-local" required /></label><label className={styles.field}>Actual start (UTC, optional)<input name="actualStartAt" type="datetime-local" /></label><label className={styles.field}>Actual end (UTC, optional)<input name="actualEndAt" type="datetime-local" /></label>
      <fieldset className={`${styles.field} ${styles.full}`}><legend>Affected services</legend><div className={styles.checks}>{formData.data.services.map((service) => <label className={styles.check} key={service.id}><input type="checkbox" name="serviceIds" value={service.id} />{service.nameEn}</label>)}</div></fieldset>
      <div className={`${styles.checks} ${styles.full}`}><label className={styles.check}><input type="checkbox" name="affectsUptime" defaultChecked={formData.data.plannedMaintenanceAffectsUptime} />Counts as downtime</label><label className={styles.check}><input type="checkbox" name="publish" />Publish now</label></div><button className={`${styles.button} ${styles.full}`}>Create maintenance</button>
    </form></section>}
    <section className={styles.panel}><h2>Maintenance schedule</h2>{!records.available ? <Unavailable message={records.message} /> : <div className={styles.list}>{records.data.length ? records.data.map((item) => <div className={`${styles.row} ${styles.eventRow}`} key={item.id}><div><strong>{item.titleEn}</strong><small>{item.status} · {item.isPublished ? "Published" : "Draft"} · {item.scheduledStartAt.toLocaleString("en-GB", { timeZone: "UTC" })} UTC</small></div><details className={styles.eventActions}><summary>Update</summary><form action={updateMaintenance} className={styles.compactForm}><input type="hidden" name="id" value={item.id} /><label className={styles.field}>Status<select name="status" defaultValue={item.status}><option value="scheduled">Scheduled</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label className={styles.field}>Actual start (UTC)<input name="actualStartAt" type="datetime-local" /></label><label className={styles.field}>Actual end (UTC)<input name="actualEndAt" type="datetime-local" /></label>{!item.isPublished && <label className={styles.check}><input type="checkbox" name="publish" />Publish maintenance</label>}<button className={styles.button}>Save update</button></form><form action={archiveEvent}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="type" value="maintenance" /><button className={styles.dangerButton}>Archive and remove from uptime</button></form></details></div>) : <div className={styles.empty}>No maintenance scheduled.</div>}</div>}</section>
  </>;
}
