import type { Locale } from "./config";

const dictionaries = {
  en: {
    metadata: { title: "EIS Service Status", description: "Availability and operational updates for EIS services." }, brand: "EIS Service Status", skip: "Skip to main content", subscribe: "Subscribe to updates", language: "Italiano", admin: "Admin panel",
    liveHealth: "Current service health", overview: "Service status", overall: { operational: "All systems operational", degraded: "Some services are experiencing issues", outage: "Service disruption in progress", maintenance: "Planned maintenance in progress" }, intro: "Current availability and the latest operational updates for EIS services.", lastUpdated: "Last updated", live: "Current",
    servicesEyebrow: "Platform services", servicesTitle: "Service availability", last60Days: "Last {days} days", uptime: "uptime", uptimePeriod: "Uptime period", days: "days", daysAgo: "{days} days ago", today: "Today", expandCategory: "Expand category", collapseCategory: "Collapse category", noDayEvents: "No incidents or maintenance", dayEvents: "Events affecting this service",
    status: { operational: "Operational", degraded: "Degraded performance", outage: "Major outage", maintenance: "Under maintenance" }, historyLegend: "Availability history legend", availability: { operational: "Operational day", degraded: "Degraded day", outage: "Outage day", maintenance: "Maintenance day" },
    activeEyebrow: "Needs attention", activeTitle: "Active incidents", noActive: "No active incidents", noActiveBody: "There are no unresolved incidents at this time.", maintenanceEyebrow: "Planned work", maintenanceTitle: "Upcoming maintenance", maintenancePreviewWindow: "Starting within the next {days} days", noMaintenance: "No maintenance scheduled", recentEyebrow: "Past events", recentTitle: "Recent history", viewDetails: "View details", scheduledFor: "Scheduled for", affectedServices: "Affected services", update: "Update",
    incidentsMetadata: { title: "Incident history · EIS", description: "Published incident history for EIS services." }, maintenanceMetadata: { title: "Maintenance history · EIS", description: "Published maintenance history for EIS services." }, incidentsEyebrow: "Service history", incidentsTitle: "Incident history", incidentsIntro: "Published incidents, including active and resolved events.", maintenanceHistoryEyebrow: "Service history", maintenanceHistoryTitle: "Maintenance history", maintenanceHistoryIntro: "Published scheduled, active, completed, and cancelled maintenance.", noIncidents: "No published incidents yet.", noMaintenanceHistory: "No published maintenance yet.", viewAllIncidents: "View all incidents", viewAllMaintenance: "View all maintenance", paginationLabel: "History pagination", previousPage: "Previous", nextPage: "Next", pageCount: "Page {page} of {pages}",
    resolved: "Resolved", monitoring: "Monitoring", identified: "Identified", investigating: "Investigating", scheduled: "Scheduled", inProgress: "In progress", completed: "Completed", cancelled: "Cancelled", started: "Started", ended: "Ended", duration: "Duration", incident: "Incident", maintenance: "Maintenance", timeline: "Event timeline", back: "Back to service status",
    footerNote: "Service status information from EIS.", subscribeTitle: "Stay informed", subscribeBody: "Receive a message when EIS publishes an incident or planned maintenance update.",
  },
  it: {
    metadata: { title: "Stato dei servizi EIS", description: "Disponibilità e aggiornamenti operativi sui servizi EIS." }, brand: "Stato dei servizi EIS", skip: "Vai al contenuto principale", subscribe: "Iscriviti agli aggiornamenti", language: "English", admin: "Pannello admin",
    liveHealth: "Stato attuale dei servizi", overview: "Stato dei servizi", overall: { operational: "Tutti i sistemi sono operativi", degraded: "Alcuni servizi presentano problemi", outage: "È in corso un'interruzione del servizio", maintenance: "Manutenzione pianificata in corso" }, intro: "Disponibilità attuale e ultimi aggiornamenti operativi sui servizi EIS.", lastUpdated: "Ultimo aggiornamento", live: "Attuale",
    servicesEyebrow: "Servizi della piattaforma", servicesTitle: "Disponibilità dei servizi", last60Days: "Ultimi {days} giorni", uptime: "disponibilità", uptimePeriod: "Periodo disponibilità", days: "giorni", daysAgo: "{days} giorni fa", today: "Oggi", expandCategory: "Espandi categoria", collapseCategory: "Comprimi categoria", noDayEvents: "Nessun incidente o manutenzione", dayEvents: "Eventi che hanno interessato questo servizio",
    status: { operational: "Operativo", degraded: "Prestazioni ridotte", outage: "Interruzione grave", maintenance: "In manutenzione" }, historyLegend: "Legenda dello storico disponibilità", availability: { operational: "Giorno operativo", degraded: "Giorno con prestazioni ridotte", outage: "Giorno con interruzione", maintenance: "Giorno di manutenzione" },
    activeEyebrow: "Richiede attenzione", activeTitle: "Incidenti attivi", noActive: "Nessun incidente attivo", noActiveBody: "Al momento non ci sono incidenti irrisolti.", maintenanceEyebrow: "Attività pianificate", maintenanceTitle: "Manutenzioni programmate", maintenancePreviewWindow: "In programma nei prossimi {days} giorni", noMaintenance: "Nessuna manutenzione programmata", recentEyebrow: "Eventi passati", recentTitle: "Cronologia recente", viewDetails: "Vedi dettagli", scheduledFor: "Programmato per", affectedServices: "Servizi interessati", update: "Aggiornamento",
    incidentsMetadata: { title: "Cronologia degli incidenti · EIS", description: "Cronologia degli incidenti pubblicati per i servizi EIS." }, maintenanceMetadata: { title: "Cronologia delle manutenzioni · EIS", description: "Cronologia delle manutenzioni pubblicate per i servizi EIS." }, incidentsEyebrow: "Cronologia dei servizi", incidentsTitle: "Cronologia degli incidenti", incidentsIntro: "Incidenti pubblicati, inclusi gli eventi attivi e risolti.", maintenanceHistoryEyebrow: "Cronologia dei servizi", maintenanceHistoryTitle: "Cronologia delle manutenzioni", maintenanceHistoryIntro: "Manutenzioni pubblicate, programmate, in corso, completate e annullate.", noIncidents: "Non ci sono ancora incidenti pubblicati.", noMaintenanceHistory: "Non ci sono ancora manutenzioni pubblicate.", viewAllIncidents: "Vedi tutti gli incidenti", viewAllMaintenance: "Vedi tutte le manutenzioni", paginationLabel: "Paginazione della cronologia", previousPage: "Precedente", nextPage: "Successiva", pageCount: "Pagina {page} di {pages}",
    resolved: "Risolto", monitoring: "Monitoraggio", identified: "Identificato", investigating: "In analisi", scheduled: "Programmato", inProgress: "In corso", completed: "Completato", cancelled: "Annullato", started: "Inizio", ended: "Fine", duration: "Durata", incident: "Incidente", maintenance: "Manutenzione", timeline: "Cronologia dell'evento", back: "Torna allo stato dei servizi",
    footerNote: "Informazioni sullo stato dei servizi EIS.", subscribeTitle: "Rimani aggiornato", subscribeBody: "Ricevi un messaggio quando EIS pubblica un incidente o un aggiornamento sulla manutenzione pianificata.",
  },
} as const;

export type Dictionary = (typeof dictionaries)[Locale];
export function getDictionary(locale: Locale): Dictionary { return dictionaries[locale]; }
