import { archiveEvent, createIncident, updateIncident } from "@/modules/admin/actions";
import { loadEventFormData, loadIncidents } from "@/modules/admin/data";
import { requireAdmin } from "@/modules/auth/guard";
import { Notice, PageHeader, Unavailable } from "../_components";
import styles from "../admin.module.css";

export default async function IncidentsPage({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string }> }) {
  await requireAdmin();
  const [formData, records, params] = await Promise.all([loadEventFormData(), loadIncidents(), searchParams]);
  return <><PageHeader title="Incidents" description="Record service interruptions manually. Published, uptime-affecting incidents update stored availability." /><Notice {...params} />
    {!formData.available ? <Unavailable message={formData.message} /> : <section className={styles.panel}><h2>Create incident</h2><form action={createIncident} className={styles.form}>
      <label className={styles.field}>Slug<input name="slug" required /></label><label className={styles.field}>Status<select name="status"><option value="investigating">Investigating</option><option value="identified">Identified</option><option value="monitoring">Monitoring</option><option value="resolved">Resolved</option></select></label>
      <label className={styles.field}>English title<input name="titleEn" required /></label><label className={styles.field}>Italian title<input name="titleIt" required /></label><label className={styles.field}>English description<textarea name="descriptionEn" /></label><label className={styles.field}>Italian description<textarea name="descriptionIt" /></label>
      <label className={styles.field}>Started at (UTC)<input name="startedAt" type="datetime-local" required /></label><label className={styles.field}>Resolved at (UTC, optional)<input name="resolvedAt" type="datetime-local" /></label>
      <fieldset className={`${styles.field} ${styles.full}`}><legend>Affected services</legend><div className={styles.checks}>{formData.data.services.map((service) => <label className={styles.check} key={service.id}><input type="checkbox" name="serviceIds" value={service.id} />{service.nameEn}</label>)}</div></fieldset>
      <div className={`${styles.checks} ${styles.full}`}><label className={styles.check}><input type="checkbox" name="affectsUptime" defaultChecked />Counts as downtime</label><label className={styles.check}><input type="checkbox" name="publish" />Publish now</label></div><button className={`${styles.button} ${styles.full}`}>Create incident</button>
    </form></section>}
    <section className={styles.panel}><h2>Recent incidents</h2>{!records.available ? <Unavailable message={records.message} /> : <div className={styles.list}>{records.data.length ? records.data.map((item) => <div className={`${styles.row} ${styles.eventRow}`} key={item.id}><div><strong>{item.titleEn}</strong><small>{item.status} · {item.isPublished ? "Published" : "Draft"} · {item.startedAt.toLocaleString("en-GB", { timeZone: "UTC" })} UTC</small></div><details className={styles.eventActions}><summary>Update</summary><form action={updateIncident} className={styles.compactForm}><input type="hidden" name="id" value={item.id} /><label className={styles.field}>Status<select name="status" defaultValue={item.status}><option value="investigating">Investigating</option><option value="identified">Identified</option><option value="monitoring">Monitoring</option><option value="resolved">Resolved</option></select></label><label className={styles.field}>Resolved at (UTC)<input name="resolvedAt" type="datetime-local" /></label><label className={styles.field}>English update<textarea name="messageEn" required /></label><label className={styles.field}>Italian update<textarea name="messageIt" required /></label>{!item.isPublished && <label className={styles.check}><input type="checkbox" name="publish" />Publish incident</label>}<button className={styles.button}>Save update</button></form><form action={archiveEvent}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="type" value="incident" /><button className={styles.dangerButton}>Archive and remove from uptime</button></form></details></div>) : <div className={styles.empty}>No incidents recorded.</div>}</div>}</section>
  </>;
}
